### ISSUE TITLE
Hint to use InfluxQL

### ISSUE THREAD

**Issue by christmart** [chpro/fronius-grafana-dashboard#1]
Thanks for this Howto and the Dashboard.
After some trying I got it working.
First I tried with Flux language.
A hint in the readme to use InfluxQL  or even a sample datasource.yaml for the provisioning of the datasources would be helpful.
This is what I used:
```
apiVersion: 1

datasources:
  - name: inverter
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      # This database should be mapped to a bucket
      dbName: inverter
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token XXXXX'
```
